//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public System.Guid ID { get; set; }
        public string CourseName { get; set; }
        public string ClassID { get; set; }
        public string Teacher { get; set; }
        public string TeacherID { get; set; }
        public string Week { get; set; }
        public string CourseOrder { get; set; }
        public string Place { get; set; }
    }
}
