//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPARanking
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> HandleDept { get; set; }
        public Nullable<System.Guid> HandleStaff { get; set; }
        public string StudentID { get; set; }
        public string Name { get; set; }
        public string Major { get; set; }
        public Nullable<double> FirstYearGPA { get; set; }
        public Nullable<int> FirstYearGPARanking { get; set; }
        public Nullable<double> SecondYearGPA { get; set; }
        public Nullable<int> SecondYearGPARanking { get; set; }
        public Nullable<int> RankingChange { get; set; }
        public string ChangePercentage { get; set; }
    }
}
