//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> HandleDept { get; set; }
        public Nullable<System.Guid> HandleStaff { get; set; }
        public string IdCard { get; set; }
        public string Name { get; set; }
        public string WorkUnit { get; set; }
        public string WorkDuty { get; set; }
        public string WorkLevel { get; set; }
        public string DutyTime { get; set; }
        public string LevelTime { get; set; }
        public string WorkTime { get; set; }
        public string Gender { get; set; }
        public string Nation { get; set; }
        public string NativePlace { get; set; }
        public string BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string GrowPlace { get; set; }
        public string PartyDate { get; set; }
        public string PoliticsStatus { get; set; }
        public string Marriage { get; set; }
        public string Health { get; set; }
        public string Education { get; set; }
        public string School { get; set; }
        public string Major { get; set; }
        public string HighestEducation { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Skill { get; set; }
        public string resume { get; set; }
        public string Democratic { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string StudentID { get; set; }
        public string Height { get; set; }
    }
}
